version: 2.1
orbs:
  python: circleci/python@2.2.0
  coveralls: coveralls/coveralls@2.2.5

jobs:
  test:
    docker:
      - image: cimg/python:3.14
      - image: cimg/postgres:16.4
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: test_takehomePy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -e . coverage pytest-cov coveralls
      - run:
          name: Run tests with coverage
          command: coverage run --source=. -m pytest
      - run:
          name: Upload coverage to Coveralls
          command: coveralls

workflows:
  test:
    jobs:
      - test
