"""notification table fix

Revision ID: 40d65f90e3ad
Revises: 6387f082adde
Create Date: 2026-09-02 18:49:37.106310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d65f90e3ad'
down_revision: Union[str, Sequence[str], None] = '6387f082adde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channel', sa.String(length=20), nullable=False))
    op.drop_column('notifications', 'chanel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('chanel', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'channel')
    # ### end Alembic commands ###
